version: "3"
services:
  product_service:
    image: product_service:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  category_service:
    image: category_service:latest
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - product_service
  mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
